# Site settings
title: CV
role: Service Technician
name: Oskar Haręcki

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/pl-misuw
 - title: 
   url: 

#Any buzzword skills you want to include
skills:
 - name: CI/CD understanding
   percent: 25%
 - name: IT services
   percent: 75%
 - name: People skills
   percent: 65%
 - name: Computer Service
   percent: 85%
 - name: Linux System Administration
   percent: 25%
 - name:  Windows Core Administration
   percent: 25%

#Area of Expertise
expertise:
  - name: Focussed
    description: Ability to concentrate on a single point or task.
  - name: Goal Oriented
    description: Willingly and successfully try to do what is required.
  - name: Team Player
    description: Working great with a group to solve problems and find solutions. 
  - name: Problem Solver
    description: Know how to identify a problem, determine the root of the problem, find multiple solutions and choose the best outcome.

#Work experience is required
roles:
 - title: Service Technician
   start: 2022
   end: Ongoing
   employer: Ivy Technnology
   description: Repairing and testing hardware/software using PCDR, PowerShell and various benchamrks.
   place: Bydgoszcz, Poland
 - title: Instructor
   start: 2020
   end: 2022
   employer: McDonald’s Corporation
   description: Training new employees and preparation of training materials.
   place: Bydgoszcz, Poland
 - title: IT Consultant
   start: 2019
   end: 2020
   employer: Media System
   description: Helping businesses and organizations manage their technology use and keeping them up to date.
   place: Bydgoszcz, Poland

#Education is required
education:
 - title: School
   start: 2014
   end: 2017
   subject: Photography and Graphic Designer
   school: Vocational school

#List of interesting Github repo/projects to include - optional
github:
  - https://github.com/Oskar-Harecki/Oskar-Harecki.github.io

#Contact flair is optional
contact:
   website: https://github.com/Oskar-Harecki/Oskar-Harecki.github.io
   phone: +48 880 987 385
   email: harecki.oskar.97@gmail.com
   address1: Bydgoszcz
   address2:

intro: |
  <p>Wyrażam zgodę na przetwarzanie moich danych osobowych dla potrzeb niezbędnych do realizacji procesu rekrutacji zgodnie z Rozporządzeniem Parlamentu Europejskiego i Rady (UE) 2016/679 z dnia 27 kwietnia 2016 r. w sprawie ochrony osób fizycznych w związku z przetwarzaniem danych osobowych i w sprawie swobodnego przepływu takich danych oraz uchylenia dyrektywy 95/46/WE (RODO).</p>

  <p>I enjoy working with new technologies, like meeting interesting people and I'm very passionate about all kinds of games (computer, console, mobile and tabletop).</p>

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
    <strong>Service</strong>: I have primarily used various of testing tools, console command and benchamrks for testing new and used computers both desktop and laptops.<br/><br/>
    <strong>Game Test</strong>: I have some basic knowledge of game-testing, I've recently signed up to participate in couple game tests using gametester.gg by Lionbridge Games Studios<br/><br/>

