# Site settings
title: CV
role: Service Technician
name: Oskar Haręcki

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/pl-misuw
 - title: LinkedIn
   url: https://www.linkedin.com/in/michał-s-aa43a89b/

#Any buzzword skills you want to include
skills:
 - name: CI/CD understanding
   percent: 25%
 - name: IT services
   percent: 75%
 - name: People skills
   percent: 65%
 - name: Computer Service
   percent: 85%
 - name: Linux System Administration
   percent: 25%
 - name:  Windows Core Administration
   percent: 25%

#Area of Expertise
expertise:
  - name: Focussed
    description: Ability to concentrate on a single point or task.
  - name: Goal Oriented
    description: Willingly and successfully try to do what is required.
  - name: Team Player
    description: Working great with a group to solve problems and find solutions. 
  - name: Problem Solver
    description: Know how to identify a problem, determine the root of the problem, find multiple solutions and choose the best outcome.

#Work experience is required
roles:
 - title: Service Technician
   start: 2022
   end: Ongoing
   employer: Ivy Technnology
   description: Repairing and testing hardware/software using PCDR, PowerShell and various benchamrks.
   place: Bydgoszcz, Poland
 - title: Instructor
   start: 2020
   end: 2022
   employer: McDonald’s Corporation
   description: Training new employees and preparation of training materials.
   place: Bydgoszcz, Poland
 - title: IT Consultant
   start: 2019
   end: 2020
   employer: Media System
   description: Helping businesses and organizations manage their technology use and keeping them up to date.
   place: Bydgoszcz, Poland

#Education is required
education:
 - title: School
   start: 2014
   end: 2017
   subject: Photography and Graphic Designer
   school: Vocational school

#List of interesting Github repo/projects to include - optional
github:
  - https://github.com/Oskar-Harecki/Oskar-Harecki.github.io

#Contact flair is optional
contact:
   website: https://github.com/Oskar-Harecki/Oskar-Harecki.github.io
   phone: +48 880 987 385
   email: harecki.oskar.97@gmail.com
   address1: Bydgoszcz
   address2:

intro: |
  <p>I am an engineer with 5 years’ experience working in technology. I have primarily worked on the Windows-related web stack, but have worked across a broad range of technologies thereon: Groovy, Linux, Docker and most recently Openshift and Kubernetes; as well as spending a reasonable amount of time building applications for the web, which has given me an exposure to a range of web-related skills (Graphic design, coding, services, workflows, AWS integrations).</p>

  <p>I enjoy working with interesting products, with understanding of business-related topics, management and emphasis on DevOps culture. Due to my work with consultancy agencies I have a strong understanding of processes, engineering principals and communication with clients and stakeholders.</p>

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
    <strong>Cloud platforms</strong>: I have primarily used AWS for running production apps on the cloud. I have experience setting up, configuring and running applications using a range of AWS offerings, including EC2, RDS, S3, Cogito, Lambda.<br/><br/>
    <strong>Web Development</strong>: Through building web applications, I have also worked with various client side technology, having used jQuery, Bootstrap, LESS, SASS.<br/><br/>
    <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar, Jenkins, TeamCity, etc. I have experience with an array of testing tools and technologies.<br/><br/>
